--------------------------------------------------------
--  파일이 생성됨 - 화요일-2월-06-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CROSSFIT_BOARD
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CROSSFIT_BOARD" 
   (	"POST_ID" NUMBER, 
	"TITLE" VARCHAR2(255 BYTE), 
	"CONTENT" CLOB, 
	"CREATION_DATE" DATE DEFAULT SYSDATE, 
	"MODIFICATION_DATE" DATE, 
	"VIEW_COUNT" NUMBER DEFAULT 0, 
	"MEMBER_ID" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table CROSSFIT_COMMENTS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CROSSFIT_COMMENTS" 
   (	"COMMENT_ID" NUMBER, 
	"POST_ID" NUMBER, 
	"MEMBER_ID" VARCHAR2(50 BYTE), 
	"COMMENT_TEXT" CLOB, 
	"CREATION_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("COMMENT_TEXT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table CROSSFITMEMBERS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CROSSFITMEMBERS" 
   (	"MEMBER_ID" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE), 
	"FULL_NAME" VARCHAR2(50 BYTE), 
	"PHONE_NUMBER" VARCHAR2(20 BYTE), 
	"GENDER" VARCHAR2(10 BYTE), 
	"BIRTH_DATE" DATE, 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"REGISTRATION_DATE" DATE DEFAULT NULL, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"MEMBERSHIP_TYPE" VARCHAR2(20 BYTE), 
	"HOBBY" VARCHAR2(50 BYTE), 
	"CMT" VARCHAR2(255 BYTE), 
	"CNT" NUMBER DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.CROSSFIT_BOARD
SET DEFINE OFF;
Insert into SYSTEM.CROSSFIT_BOARD (POST_ID,TITLE,CREATION_DATE,MODIFICATION_DATE,VIEW_COUNT,MEMBER_ID) values (1,'dddㅇㅇ',to_date('24/02/06','RR/MM/DD'),to_date('24/02/06','RR/MM/DD'),0,'hommefatale');
Insert into SYSTEM.CROSSFIT_BOARD (POST_ID,TITLE,CREATION_DATE,MODIFICATION_DATE,VIEW_COUNT,MEMBER_ID) values (2,'1ㄱㄱㅂㅈㄱ',to_date('24/02/06','RR/MM/DD'),to_date('24/02/06','RR/MM/DD'),0,'tmvldksk1');
Insert into SYSTEM.CROSSFIT_BOARD (POST_ID,TITLE,CREATION_DATE,MODIFICATION_DATE,VIEW_COUNT,MEMBER_ID) values (3,'QWDQWD',to_date('24/02/06','RR/MM/DD'),to_date('24/02/06','RR/MM/DD'),0,'tmvldksk1');
REM INSERTING into SYSTEM.CROSSFIT_COMMENTS
SET DEFINE OFF;
REM INSERTING into SYSTEM.CROSSFITMEMBERS
SET DEFINE OFF;
Insert into SYSTEM.CROSSFITMEMBERS (MEMBER_ID,PASSWORD,FULL_NAME,PHONE_NUMBER,GENDER,BIRTH_DATE,ADDRESS,REGISTRATION_DATE,START_DATE,END_DATE,MEMBERSHIP_TYPE,HOBBY,CMT,CNT) values ('tmvldksk1','123123','승회원','01029594125','남성',to_date('96/01/01','RR/MM/DD'),'항동',to_date('24/02/08','RR/MM/DD'),null,null,'일반회원','qw','qwdqwd',0);
Insert into SYSTEM.CROSSFITMEMBERS (MEMBER_ID,PASSWORD,FULL_NAME,PHONE_NUMBER,GENDER,BIRTH_DATE,ADDRESS,REGISTRATION_DATE,START_DATE,END_DATE,MEMBERSHIP_TYPE,HOBBY,CMT,CNT) values ('test123','123123','승코치','01029591231','여성',to_date('96/01/01','RR/MM/DD'),'항동',null,null,null,'코치님','qw',null,0);
Insert into SYSTEM.CROSSFITMEMBERS (MEMBER_ID,PASSWORD,FULL_NAME,PHONE_NUMBER,GENDER,BIRTH_DATE,ADDRESS,REGISTRATION_DATE,START_DATE,END_DATE,MEMBERSHIP_TYPE,HOBBY,CMT,CNT) values ('hommefatale','123123','승대표','01029591312','여성',to_date('96/01/01','RR/MM/DD'),'항동',to_date('24/02/09','RR/MM/DD'),to_date('24/02/22','RR/MM/DD'),to_date('24/03/07','RR/MM/DD'),'대표님','고기먹기','wefewf',0);
--------------------------------------------------------
--  DDL for Index SYS_C007635
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007635" ON "SYSTEM"."CROSSFIT_BOARD" ("POST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007636
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007636" ON "SYSTEM"."CROSSFIT_COMMENTS" ("COMMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007615
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007615" ON "SYSTEM"."CROSSFITMEMBERS" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CROSSFIT_BOARD
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CROSSFIT_BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CROSSFIT_BOARD" ADD PRIMARY KEY ("POST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CROSSFIT_COMMENTS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CROSSFIT_COMMENTS" ADD PRIMARY KEY ("COMMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CROSSFITMEMBERS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CROSSFITMEMBERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CROSSFITMEMBERS" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CROSSFITMEMBERS" MODIFY ("FULL_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CROSSFITMEMBERS" MODIFY ("BIRTH_DATE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CROSSFITMEMBERS" ADD PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CROSSFITMEMBERS" MODIFY ("CNT" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CROSSFIT_COMMENTS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CROSSFIT_COMMENTS" ADD CONSTRAINT "FK_COMMENTS_POST" FOREIGN KEY ("POST_ID")
	  REFERENCES "SYSTEM"."CROSSFIT_BOARD" ("POST_ID") ENABLE;
  ALTER TABLE "SYSTEM"."CROSSFIT_COMMENTS" ADD CONSTRAINT "FK_COMMENTS_MEMBER" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "SYSTEM"."CROSSFITMEMBERS" ("MEMBER_ID") ENABLE;
